export const domainCategoryMap: Record<string, string[]> = {
  // Social Media
  "twitter.com":        ["Social Media", "Social"],
  "x.com":              ["Social Media", "Social"],
  "instagram.com":      ["Social Media", "Social"],
  "reddit.com":         ["Social Media", "Social"],
  "linkedin.com":       ["Social Media", "Professional", "Social"],
  "facebook.com":       ["Social Media", "Social"],
  "tiktok.com":         ["Social Media", "Social", "Entertainment"],
  "discord.com":        ["Social Media", "Social", "Gaming"],
  "snapchat.com":       ["Social Media", "Social"],
  "pinterest.com":      ["Social Media", "Social", "Design"],
  "threads.net":        ["Social Media", "Social"],
  "telegram.org":       ["Social Media", "Social"],
  "whatsapp.com":       ["Social Media", "Social"],
  "mastodon.social":    ["Social Media", "Social"],
  "bsky.app":           ["Social Media", "Social"],
  "quora.com":          ["Social Media", "Social"],
  "tumblr.com":         ["Social Media", "Social"],

  // Productivity
  "notion.so":          ["Productivity", "Tools"],
  "notion.site":        ["Productivity", "Tools"],
  "trello.com":         ["Productivity", "Tools"],
  "asana.com":          ["Productivity", "Tools"],
  "todoist.com":        ["Productivity", "Tools"],
  "clickup.com":        ["Productivity", "Tools"],
  "linear.app":         ["Productivity", "Development"],
  "airtable.com":       ["Productivity", "Tools"],
  "slack.com":          ["Productivity", "Communication", "Tools"],
  "zoom.us":            ["Productivity", "Communication"],
  "meet.google.com":    ["Productivity", "Communication"],
  "teams.microsoft.com": ["Productivity", "Communication"],
  "office.com":         ["Productivity", "Tools"],
  "outlook.live.com":   ["Productivity", "Email"],
  "outlook.office.com": ["Productivity", "Email"],
  "mail.google.com":    ["Productivity", "Email"],
  "drive.google.com":   ["Productivity", "Cloud Storage"],
  "calendar.google.com": ["Productivity"],
  "docs.google.com":    ["Productivity"],
  "sheets.google.com":  ["Productivity"],
  "keep.google.com":    ["Productivity"],
  "evernote.com":       ["Productivity", "Notes"],
  "miro.com":           ["Productivity", "Tools"],
  "basecamp.com":       ["Productivity", "Tools"],
  "1password.com":      ["Productivity", "Tools"],
  "lastpass.com":       ["Productivity", "Tools"],
  "bitwarden.com":      ["Productivity", "Tools"],
  "calendly.com":       ["Productivity", "Tools"],
  "loom.com":           ["Productivity", "Communication"],
  "notion.ai":          ["Productivity", "Artificial Intelligence", "AI"],

  // Artificial Intelligence
  "chat.openai.com":    ["Artificial Intelligence", "AI", "AI Models"],
  "chatgpt.com":        ["Artificial Intelligence", "AI", "AI Models"],
  "perplexity.ai":      ["Artificial Intelligence", "AI", "AI Models"],
  "claude.ai":          ["Artificial Intelligence", "AI", "AI Models"],
  "gemini.google.com":  ["Artificial Intelligence", "AI", "AI Models"],
  "copilot.microsoft.com": ["Artificial Intelligence", "AI"],
  "huggingface.co":     ["Artificial Intelligence", "AI", "Development"],
  "midjourney.com":     ["Artificial Intelligence", "AI", "Design"],
  "stability.ai":       ["Artificial Intelligence", "AI"],
  "grok.com":           ["Artificial Intelligence", "AI", "AI Models"],
  "x.ai":               ["Artificial Intelligence", "AI"],
  "fireworks.ai":       ["Artificial Intelligence", "AI", "Development"],
  "together.ai":        ["Artificial Intelligence", "AI"],
  "replicate.com":      ["Artificial Intelligence", "AI", "Development"],
  "anthropic.com":      ["Artificial Intelligence", "AI"],
  "openai.com":         ["Artificial Intelligence", "AI"],
  "elevenlabs.io":      ["Artificial Intelligence", "AI"],
  "synthesia.io":       ["Artificial Intelligence", "AI"],
  "runwayml.com":       ["Artificial Intelligence", "AI", "Design"],

  // Development
  "github.com":         ["Development", "Coding", "Dev Tools"],
  "gitlab.com":         ["Development", "Coding"],
  "bitbucket.org":      ["Development", "Coding"],
  "stackoverflow.com":  ["Development", "Coding"],
  "stackexchange.com":  ["Development", "Coding"],
  "vercel.com":         ["Development", "Coding"],
  "netlify.com":        ["Development", "Coding"],
  "cloudflare.com":     ["Development", "Coding"],
  "npmjs.com":          ["Development", "Coding"],
  "python.org":         ["Development", "Coding"],
  "react.dev":          ["Development", "Coding"],
  "nextjs.org":         ["Development", "Coding"],
  "nodejs.org":         ["Development", "Coding"],
  "deno.land":          ["Development", "Coding"],
  "docker.com":         ["Development", "DevOps"],
  "kubernetes.io":      ["Development", "DevOps"],
  "replit.com":         ["Development", "Coding"],
  "codepen.io":         ["Development", "Coding"],
  "codesandbox.io":     ["Development", "Coding"],
  "w3schools.com":      ["Development", "Coding"],
  "developer.mozilla.org": ["Development", "Coding"],
  "leetcode.com":       ["Development", "Placements", "Coding"],
  "hackerrank.com":     ["Development", "Placements", "Coding"],
  "codeforces.com":     ["Development", "Placements", "Coding"],
  "codechef.com":       ["Development", "Placements", "Coding"],
  "aws.amazon.com":     ["Development", "Cloud", "Coding"],
  "console.aws.amazon.com": ["Development", "Cloud"],
  "cloud.google.com":   ["Development", "Cloud"],
  "portal.azure.com":   ["Development", "Cloud"],
  "terraform.io":       ["Development", "DevOps"],
  "ansible.com":        ["Development", "DevOps"],
  "jenkins.io":         ["Development", "DevOps"],
  "grafana.com":        ["Development", "DevOps"],
  "datadoghq.com":      ["Development", "DevOps"],
  "supabase.com":       ["Development", "Coding"],
  "firebase.google.com": ["Development", "Coding"],
  "mongodb.com":        ["Development", "Coding"],
  "postgresql.org":     ["Development", "Coding"],
  "sqlite.org":         ["Development", "Coding"],
  "redis.io":           ["Development", "Coding"],

  // Design & Creative
  "figma.com":          ["Design", "Creative", "Productivity"],
  "canva.com":          ["Design", "Creative"],
  "dribbble.com":       ["Design", "Creative"],
  "behance.net":        ["Design", "Creative"],
  "adobe.com":          ["Design", "Creative"],
  "color.adobe.com":    ["Design", "Creative"],
  "unsplash.com":       ["Design", "Photography"],
  "pexels.com":         ["Design", "Photography"],
  "pixabay.com":        ["Design", "Photography"],
  "freepik.com":        ["Design", "Creative"],
  "flaticon.com":       ["Design", "Creative"],
  "coolors.co":         ["Design", "Creative"],
  "sketch.com":         ["Design", "Creative"],
  "blender.org":        ["Design", "Creative", "Development"],
  "photopea.com":       ["Design", "Creative"],

  // Entertainment
  "youtube.com":        ["Entertainment", "Video"],
  "netflix.com":        ["Entertainment", "Streaming"],
  "spotify.com":        ["Entertainment", "Music"],
  "twitch.tv":          ["Entertainment", "Gaming"],
  "hulu.com":           ["Entertainment", "Streaming"],
  "disneyplus.com":     ["Entertainment", "Streaming"],
  "primevideo.com":     ["Entertainment", "Streaming"],
  "hbomax.com":         ["Entertainment", "Streaming"],
  "imdb.com":           ["Entertainment", "Movies"],
  "soundcloud.com":     ["Entertainment", "Music"],
  "apple.com":          ["Entertainment", "Technology"],
  "tv.apple.com":       ["Entertainment", "Streaming"],
  "music.apple.com":    ["Entertainment", "Music"],
  "letterboxd.com":     ["Entertainment", "Movies"],
  "myanimelist.net":    ["Entertainment", "Anime"],
  "crunchyroll.com":    ["Entertainment", "Anime"],
  "bandcamp.com":       ["Entertainment", "Music"],
  "tidal.com":          ["Entertainment", "Music"],
  "deezer.com":         ["Entertainment", "Music"],
  "last.fm":            ["Entertainment", "Music"],

  // News & Media
  "bbc.com":            ["News & Media", "News"],
  "bbc.co.uk":          ["News & Media", "News"],
  "cnn.com":            ["News & Media", "News"],
  "reuters.com":        ["News & Media", "News"],
  "nytimes.com":        ["News & Media", "News"],
  "theguardian.com":    ["News & Media", "News"],
  "bloomberg.com":      ["News & Media", "Finance", "News"],
  "wsj.com":            ["News & Media", "Finance", "News"],
  "washingtonpost.com": ["News & Media", "News"],
  "npr.org":            ["News & Media", "News"],
  "apnews.com":         ["News & Media", "News"],
  "axios.com":          ["News & Media", "News"],
  "politico.com":       ["News & Media", "Politics"],
  "yahoo.com":          ["News & Media", "News"],
  "news.google.com":    ["News & Media", "News"],
  "techcrunch.com":     ["News & Media", "Technology"],
  "theverge.com":       ["News & Media", "Technology"],
  "wired.com":          ["News & Media", "Technology"],
  "arstechnica.com":    ["News & Media", "Technology"],
  "engadget.com":       ["News & Media", "Technology"],
  "medium.com":         ["News & Media", "Productivity"],
  "substack.com":       ["News & Media", "Productivity"],

  // Sports
  "espn.com":           ["Sports"],
  "skysports.com":       ["Sports"],
  "espncricinfo.com":   ["Sports", "Cricket"],
  "nba.com":            ["Sports", "Basketball"],
  "nfl.com":            ["Sports"],
  "mlb.com":            ["Sports"],
  "nhl.com":            ["Sports"],
  "formula1.com":       ["Sports", "Motorsport"],
  "f1.com":             ["Sports", "Motorsport"],
  "the-athletic.com":   ["Sports"],
  "bleacherreport.com": ["Sports"],
  "fancode.com":        ["Sports"],
  "livescore.com":      ["Sports"],
  "sports.yahoo.com":   ["Sports"],
  "cricbuzz.com":       ["Sports", "Cricket"],
  "flashscore.com":     ["Sports"],
  "transfermarkt.com":  ["Sports", "Football"],
  "goal.com":           ["Sports", "Football"],
  "soccerway.com":      ["Sports", "Football"],

  // Gaming
  "chess.com":          ["Games", "Gaming"],
  "lichess.org":        ["Games", "Gaming"],
  "steampowered.com":   ["Games", "Gaming"],
  "steamcommunity.com": ["Games", "Gaming"],
  "epicgames.com":      ["Games", "Gaming"],
  "roblox.com":         ["Games", "Gaming"],
  "minecraft.net":      ["Games", "Gaming"],
  "skribbl.io":         ["Games", "Gaming"],
  "geoguessr.com":      ["Games", "Gaming"],
  "op.gg":              ["Games", "League of Legends"],
  "dotabuff.com":       ["Games", "Dota 2"],
  "hltv.org":           ["Games", "CS"],
  "newgrounds.com":     ["Games", "Gaming"],
  "kongregate.com":     ["Games", "Gaming"],
  "armorgames.com":     ["Games", "Gaming"],
  "wordle.nytimes.com": ["Games", "Word Games"],
  "chessable.com":      ["Games", "Gaming"],

  // Shopping
  "amazon.com":         ["Shopping"],
  "amazon.in":          ["Shopping"],
  "amazon.co.uk":       ["Shopping"],
  "amazon.de":          ["Shopping"],
  "ebay.com":           ["Shopping"],
  "etsy.com":           ["Shopping"],
  "walmart.com":        ["Shopping"],
  "target.com":         ["Shopping"],
  "bestbuy.com":        ["Shopping", "Electronics"],
  "aliexpress.com":     ["Shopping"],
  "flipkart.com":       ["Shopping"],
  "myntra.com":         ["Shopping", "Fashion"],
  "ajio.com":           ["Shopping", "Fashion"],
  "nykaa.com":          ["Shopping", "Beauty"],
  "shopify.com":        ["Shopping", "E-commerce"],
  "newegg.com":         ["Shopping", "Electronics"],
  "homedepot.com":      ["Shopping", "Home Improvement"],
  "ikea.com":           ["Shopping", "Furniture"],
  "zara.com":           ["Shopping", "Fashion"],
  "nike.com":           ["Shopping", "Fashion", "Sports"],
  "adidas.com":         ["Shopping", "Fashion", "Sports"],

  // Cloud Storage
  "mega.nz":            ["Cloud Storage"],
  "dropbox.com":        ["Cloud Storage"],
  "onedrive.live.com":  ["Cloud Storage"],
  "icloud.com":         ["Cloud Storage"],
  "box.com":            ["Cloud Storage"],
  "pcloud.com":         ["Cloud Storage"],

  // Education / Learning
  "udemy.com":          ["Courses", "Education", "Learning"],
  "coursera.org":       ["Courses", "Education", "Learning"],
  "edx.org":            ["Courses", "Education", "Learning"],
  "khanacademy.org":    ["Courses", "Education", "Learning"],
  "skillshare.com":     ["Courses", "Education", "Learning"],
  "pluralsight.com":    ["Courses", "Education", "Learning"],
  "datacamp.com":       ["Courses", "Education", "Data Science"],
  "brilliant.org":      ["Courses", "Education", "Learning"],
  "codecademy.com":     ["Courses", "Coding", "Development"],
  "freecodecamp.org":   ["Courses", "Coding", "Development"],
  "theodinproject.com": ["Courses", "Coding", "Development"],
  "academia.edu":       ["Education", "Research"],
  "scholar.google.com": ["Education", "Research"],
  "researchgate.net":   ["Education", "Research"],
  "wikipedia.org":      ["Education", "Reference"],
  "wiktionary.org":     ["Education", "Reference"],
  "wikihow.com":        ["Education", "Reference"],

  // Finance
  "investing.com":      ["Finance", "News"],
  "tradingview.com":    ["Finance", "Investing"],
  "coingecko.com":      ["Finance", "Crypto"],
  "coinmarketcap.com":  ["Finance", "Crypto"],
  "binance.com":        ["Finance", "Crypto"],
  "coinbase.com":       ["Finance", "Crypto"],
  "robinhood.com":      ["Finance", "Investing"],
  "zerodha.com":        ["Finance", "Investing"],
  "groww.in":           ["Finance", "Investing"],
  "paypal.com":         ["Finance", "Payments"],
  "stripe.com":         ["Finance", "Payments", "Development"],
  "mint.com":           ["Finance", "Budgeting"],

  // Travel
  "airbnb.com":         ["Travel", "Trips"],
  "booking.com":        ["Travel", "Trips"],
  "hotels.com":         ["Travel", "Trips"],
  "expedia.com":        ["Travel", "Trips"],
  "skyscanner.net":     ["Travel", "Trips"],
  "google.com/travel":  ["Travel", "Trips"],
  "tripadvisor.com":    ["Travel", "Trips"],
  "uber.com":           ["Travel", "Transport"],
  "lyft.com":           ["Travel", "Transport"],
  "rome2rio.com":       ["Travel", "Trips"],
  "maps.google.com":    ["Travel", "Maps"],
  "openstreetmap.org":  ["Travel", "Maps"],

  // Health & Fitness
  "strava.com":         ["Health", "Fitness"],
  "myfitnesspal.com":   ["Health", "Fitness", "Nutrition"],
  "fitbit.com":         ["Health", "Fitness"],
  "nike.com/run":       ["Health", "Fitness"],
  "headspace.com":      ["Health", "Wellness", "Mental Health"],
  "calm.com":           ["Health", "Wellness", "Mental Health"],

};
